version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - chat-network

  chat-service:
    build:
      context: .
      dockerfile: ChatService.API/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__ConnectionString=redis:6379
    depends_on:
      - redis
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  redis-data: